Repository decred/politeiagui, pull requests merged in 2021-09, with the labels that each got.

#2572 feat: Add flat mode explainer.
  src/containers/Comments/Comments.jsx
  src/containers/Comments/Comments.module.css
Labels: release-blocker

#2541 fix: Show login modal when user session expires.
  src/actions/api.js
  src/actions/tests/api.test.js
  src/components/CommentForm/CommentForm.jsx
  src/components/ModalLogin.jsx
  src/components/ModalProvider.jsx
  src/components/ProposalForm/ProposalForm.jsx
  src/containers/User/Login/Form.jsx
  src/containers/User/SessionChecker/SessionChecker.jsx
  src/containers/User/SessionChecker/hooks.js
  src/hooks/api/useComments.js
  src/hooks/api/useNavigation.js
  src/lib/api.js
  src/lib/errors.js
  src/reducers/app.js
  src/reducers/tests/app.test.js
  src/selectors/app.js
  src/selectors/tests/app.test.js
  teste2e/cypress/e2e/comments/commentVotes.js
  teste2e/cypress/e2e/comments/comments.js
  teste2e/cypress/support/mock/comments.js
Labels: pi-not-deployed

#2585 proposal: Data persistence after unvetted logout.
  src/components/ModalLogin.jsx
  src/components/WhatAreYourThoughts/WhatAreYourThoughts.jsx
  src/containers/Proposal/Detail/Detail.jsx
  src/containers/Proposal/Detail/hooks.js
  src/containers/User/Login/Form.jsx
  src/lib/errors.js
  src/reducers/models/comments.js
  src/reducers/models/proposals.js
  teste2e/cypress/e2e/proposal/detail.js
  teste2e/cypress/errors.js
  teste2e/cypress/support/commands.js
Labels: release-blocker

#2591 docs: Add E2E testing tutorial.
  docs/e2e.md
Labels: 91cfcc8
